//go:build linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"runtime"

	"github.com/cilium/ebpf"
)

// connect_bpfel.o is generated by internal/netmonitor/ebpf/Makefile during
// Linux Nix package builds and embedded for runtime loading.
//
//go:embed connect_bpfel.o
var bpfObjBytes []byte

// connect_bpfel_arm64.o is generated by internal/netmonitor/ebpf/Makefile
// during Linux Nix package builds and embedded for runtime loading on arm64.
//
//go:embed connect_bpfel_arm64.o
var bpfObjBytesArm64 []byte

// EmbeddedMapDefaults returns MaxEntries from the embedded BPF object.
func EmbeddedMapDefaults() (MapOverrides, error) {
	spec, err := ebpf.LoadCollectionSpecFromReader(bytes.NewReader(bpfObjBytes))
	if err != nil {
		return MapOverrides{}, err
	}
	get := func(name string) uint32 {
		if m, ok := spec.Maps[name]; ok {
			return m.MaxEntries
		}
		return 0
	}
	return MapOverrides{
		Allow:   get("allowlist"),
		Deny:    get("denylist"),
		LPM:     get("lpm4_allow"), // assume same for lpm6
		LPMDeny: get("lpm4_deny"),  // assume same for lpm6
		Default: get("default_deny"),
	}, nil
}

// LoadConnectProgram loads the embedded BPF object, applying map size overrides if provided.
// Caller must attach the programs (handle_connect4/handle_connect6) and close the collection.
func LoadConnectProgram() (*ebpf.Collection, error) {
	obj := bpfObjBytes
	if runtime.GOARCH == "arm64" {
		if len(bpfObjBytesArm64) == 0 {
			return nil, fmt.Errorf("ebpf object missing (connect_bpfel_arm64.o)")
		}
		obj = bpfObjBytesArm64
	}
	if len(obj) == 0 {
		return nil, fmt.Errorf("ebpf object missing (connect_bpfel.o)")
	}
	spec, err := ebpf.LoadCollectionSpecFromReader(bytes.NewReader(obj))
	if err != nil {
		return nil, fmt.Errorf("load bpf spec: %w", err)
	}

	applyMapOverrides(spec)

	coll, err := ebpf.NewCollection(spec)
	if err != nil {
		return nil, fmt.Errorf("create bpf collection: %w", err)
	}
	return coll, nil
}

func applyMapOverrides(spec *ebpf.CollectionSpec) {
	if spec == nil {
		return
	}
	override := func(name string, v uint32) {
		if v == 0 {
			return
		}
		if m, ok := spec.Maps[name]; ok {
			m.MaxEntries = v
		}
	}
	override("allowlist", mapAllowOverride)
	override("denylist", mapDenyOverride)
	override("lpm4_allow", mapLPMOverride)
	override("lpm6_allow", mapLPMOverride)
	override("lpm4_deny", mapLPMDenyOverride)
	override("lpm6_deny", mapLPMDenyOverride)
	override("default_deny", mapDefaultOverride)
}
